/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

const CACHE_NAME = `cache-${version}`;

// ── BEGIN: audio cache constants (added) ──────────────────────────
// Stable, version-independent cache for audio files. Keeping the name
// out of `cache-${version}` means cached tracks survive deploys —
// users don't lose their offline music every time the app updates.
const AUDIO_CACHE_NAME = 'audio-cache-v1';
const AUDIO_EXTENSIONS = ['.mp3', '.ogg', '.wav', '.flac', '.aac', '.m4a'];

function isAudioRequest(url: URL): boolean {
	const path = url.pathname.toLowerCase();
	return AUDIO_EXTENSIONS.some((ext) => path.endsWith(ext));
}
// ── END: audio cache constants ────────────────────────────────────

// Assets generated by the build process and static files
const ASSETS = [...build, ...files];

sw.addEventListener('install', (event) => {
	event.waitUntil(
		caches
			.open(CACHE_NAME)
			.then((cache) => cache.addAll(ASSETS))
			.then(() => sw.skipWaiting())
	);
});

sw.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				// ── BEGIN: keep the audio cache + yt-thumbnails alive (added) ──
				// Whitelist any cache that isn't the previous build's app shell.
				// Audio + thumbnail caches are intentionally version-independent
				// so they survive deploys instead of being wiped every release.
				if (key === CACHE_NAME) continue;
				if (key === AUDIO_CACHE_NAME) continue;
				if (key === 'yt-thumbnails') continue;
				// Old audio cache versions (audio-cache-v0 etc.) still get nuked.
				// ── END: cache cleanup whitelist ───────────────────────────────
				await caches.delete(key);
			}
			await sw.clients.claim();
		})
	);
});

// ── Push Notifications ────────────────────────────────────────────

function ackNotification(action: string, tag: string) {
	fetch('/api/notifications/ack', {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify({ action, tag, timestamp: Date.now() })
	}).catch(() => {
		// Best-effort tracking — don't block user interaction
	});
}

sw.addEventListener('push', (event) => {
	if (!event.data) return;

	try {
		const payload = event.data.json() as {
			title: string;
			body: string;
			url?: string;
			icon?: string;
		};

		const tag = payload.url || 'missionnaire-notification';

		const options: NotificationOptions & { renotify?: boolean; actions?: { action: string; title: string; icon?: string }[] } = {
			body: payload.body,
			icon: payload.icon || '/favicon.png',
			badge: '/favicon.png',
			data: { url: payload.url || '/' },
			tag,
			renotify: true,
			actions: [
				{ action: 'open', title: 'Ouvrir' },
				{ action: 'dismiss', title: 'Ignorer' }
			]
		};

		event.waitUntil(
			sw.registration.showNotification(payload.title, options).then(() => {
				ackNotification('received', tag);
			})
		);
	} catch (e) {
		console.error('[SW] Error handling push event:', e);
	}
});

sw.addEventListener('notificationclick', (event) => {
	event.notification.close();

	const url = (event.notification.data?.url as string) || '/';
	const tag = event.notification.tag || 'unknown';
	const action = event.action || 'click';

	// Track that the user interacted with the notification
	ackNotification(action === 'dismiss' ? 'dismissed' : 'clicked', tag);

	// "dismiss" action — just close, don't navigate
	if (action === 'dismiss') return;

	event.waitUntil(
		sw.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
			// Focus an existing tab already on the target URL
			for (const client of clients) {
				if (new URL(client.url).pathname === url && 'focus' in client) {
					return client.focus();
				}
			}
			// Focus any existing tab on the same origin and navigate it
			for (const client of clients) {
				if (new URL(client.url).origin === sw.location.origin && 'focus' in client) {
					return client.focus().then((c) =>
						'navigate' in c ? c.navigate(url) : sw.clients.openWindow(url)
					);
				}
			}
			// Otherwise open a new window
			return sw.clients.openWindow(url);
		})
	);
});

// ── Fetch / Cache ─────────────────────────────────────────────────

sw.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Don't cache API requests or crawler files
	if (url.pathname.startsWith('/api/')) return;
	if (url.pathname === '/robots.txt' || url.pathname === '/sitemap.xml') return;

	// ── BEGIN: audio cache-first handler (added) ──────────────────
	// Cache-first strategy for audio files (mp3/ogg/wav/flac/aac/m4a)
	// served from any origin. Range requests are sliced from the cached
	// body so seeking/scrubbing keeps working after the file is cached.
	// On a cache miss for a Range request, we fetch the FULL file once
	// (no Range header) so subsequent plays and seeks can be served from
	// cache, then synthesise the partial response the audio element asked
	// for. This is the key to making cache + seek coexist — caching a 206
	// response and replaying it would only ever satisfy that exact range.
	if (isAudioRequest(url)) {
		event.respondWith(handleAudioFetch(event.request));
		return;
	}
	// ── END: audio cache-first handler ────────────────────────────

	// Cache YouTube thumbnails with long TTL
	if (url.hostname === 'i.ytimg.com') {
		event.respondWith(
			(async () => {
				const cache = await caches.open('yt-thumbnails');
				const cached = await cache.match(event.request);
				if (cached) return cached;

				const response = await fetch(event.request);
				if (response.ok) {
					cache.put(event.request, response.clone());
				}
				return response;
			})()
		);
		return;
	}

	// Don't cache other external URLs
	if (url.origin !== sw.location.origin) return;

	event.respondWith(
		(async () => {
			const cache = await caches.open(CACHE_NAME);

			// For build assets and static files, serve from cache first
			if (ASSETS.includes(url.pathname)) {
				const cached = await cache.match(event.request);
				if (cached) return cached;
			}

			// Navigation requests (HTML pages): stale-while-revalidate so the
			// installed app paints instantly from cache on launch instead of
			// waiting on a slow network — the cache is refreshed in the
			// background so the next visit sees fresh content. Eliminates the
			// "white screen on reopen" issue on flaky connections.
			if (event.request.mode === 'navigate') {
				const cached = await cache.match(event.request);
				const networkFetch = fetch(event.request)
					.then((response) => {
						if (response.status === 200) {
							cache.put(event.request, response.clone());
						}
						return response;
					})
					.catch(() => null);

				if (cached) {
					// Don't await — let the revalidation finish in the background.
					void networkFetch;
					return cached;
				}

				const fresh = await networkFetch;
				if (fresh) return fresh;

				const cachedIndex = await cache.match('/');
				if (cachedIndex) return cachedIndex;
				return new Response('Offline', { status: 503 });
			}

			// Subresources: network-first, fall back to cache on failure.
			try {
				const response = await fetch(event.request);
				if (response.status === 200) {
					cache.put(event.request, response.clone());
				}
				return response;
			} catch {
				const cached = await cache.match(event.request);
				if (cached) return cached;
				return new Response('Offline', { status: 503 });
			}
		})()
	);
});

// ── BEGIN: audio cache-first helpers (added) ──────────────────────
// Cache key strips method/body/Range so every variant of "play this
// track" — full GET, byte-range probe, seek-to-the-end probe — hits
// the same cached entry.
function buildAudioCacheKey(request: Request): Request {
	return new Request(request.url, { method: 'GET' });
}

async function handleAudioFetch(request: Request): Promise<Response> {
	const cache = await caches.open(AUDIO_CACHE_NAME);
	const cacheKey = buildAudioCacheKey(request);
	const rangeHeader = request.headers.get('range');

	// Cache hit — serve from disk. Slice if the audio element asked for
	// a Range so seeking after caching still produces 206 Partial Content
	// (the only thing that lets the browser scrub freely on iOS Safari).
	const cached = await cache.match(cacheKey);
	if (cached) {
		if (rangeHeader) {
			try {
				return await sliceCachedToRange(cached, rangeHeader);
			} catch {
				// Slicing failed (corrupt cache entry?) — fall through to network.
			}
		} else {
			return cached.clone();
		}
	}

	// Cache miss. Fetch the full body (no Range header) so we can store
	// the complete file and serve any future range from it. If the network
	// fails, surface a 503 so the audio element fires its `error` event
	// instead of hanging forever on a stalled request.
	let fullResponse: Response;
	try {
		fullResponse = await fetch(cacheKey);
	} catch {
		return new Response('Offline', { status: 503, statusText: 'Offline' });
	}

	if (!fullResponse.ok || fullResponse.status !== 200) {
		// Don't poison the cache with a non-200 (e.g. 403, 404, 206). Pass
		// the response straight back — the audio element will surface the
		// failure normally.
		return fullResponse;
	}

	// Store a clone, then build the response the player asked for.
	try {
		await cache.put(cacheKey, fullResponse.clone());
	} catch {
		// QuotaExceededError or similar — keep playback working even if
		// caching failed.
	}

	if (!rangeHeader) return fullResponse;

	try {
		return await sliceCachedToRange(fullResponse, rangeHeader);
	} catch {
		// If we can't slice (unparseable Range etc.), give the full body —
		// the browser will still play, just without partial-content semantics.
		return fullResponse;
	}
}

async function sliceCachedToRange(response: Response, rangeHeader: string): Promise<Response> {
	const buffer = await response.clone().arrayBuffer();
	const total = buffer.byteLength;

	// Parse "bytes=START-END" / "bytes=START-" / "bytes=-SUFFIX".
	const match = /^bytes=(\d*)-(\d*)$/i.exec(rangeHeader.trim());
	if (!match) {
		return new Response(buffer, {
			status: 200,
			headers: copyResponseHeaders(response, { 'Content-Length': String(total) })
		});
	}

	let start: number;
	let end: number;
	if (match[1] === '' && match[2] !== '') {
		// Suffix range: last N bytes.
		const suffix = Number.parseInt(match[2], 10);
		start = Math.max(0, total - suffix);
		end = total - 1;
	} else {
		start = match[1] === '' ? 0 : Number.parseInt(match[1], 10);
		end = match[2] === '' ? total - 1 : Number.parseInt(match[2], 10);
	}

	if (Number.isNaN(start) || Number.isNaN(end) || start > end || start >= total) {
		return new Response(null, {
			status: 416,
			statusText: 'Range Not Satisfiable',
			headers: { 'Content-Range': `bytes */${total}` }
		});
	}

	end = Math.min(end, total - 1);
	const chunk = buffer.slice(start, end + 1);
	const length = end - start + 1;

	return new Response(chunk, {
		status: 206,
		statusText: 'Partial Content',
		headers: copyResponseHeaders(response, {
			'Content-Range': `bytes ${start}-${end}/${total}`,
			'Content-Length': String(length),
			'Accept-Ranges': 'bytes'
		})
	});
}

function copyResponseHeaders(response: Response, overrides: Record<string, string>): Headers {
	const headers = new Headers();
	response.headers.forEach((value, key) => {
		const k = key.toLowerCase();
		// Drop length/range so callers can set fresh, accurate values.
		if (k === 'content-length' || k === 'content-range') return;
		headers.set(key, value);
	});
	for (const [k, v] of Object.entries(overrides)) headers.set(k, v);
	if (!headers.has('Accept-Ranges')) headers.set('Accept-Ranges', 'bytes');
	return headers;
}
// ── END: audio cache-first helpers ────────────────────────────────
