/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

const CACHE_NAME = `cache-${version}`;

// Assets generated by the build process and static files
const ASSETS = [...build, ...files];

sw.addEventListener('install', (event) => {
	event.waitUntil(
		caches
			.open(CACHE_NAME)
			.then((cache) => cache.addAll(ASSETS))
			.then(() => sw.skipWaiting())
	);
});

sw.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				if (key !== CACHE_NAME) {
					await caches.delete(key);
				}
			}
			await sw.clients.claim();
		})
	);
});

// ── Push Notifications ────────────────────────────────────────────

function ackNotification(action: string, tag: string) {
	fetch('/api/notifications/ack', {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify({ action, tag, timestamp: Date.now() })
	}).catch(() => {
		// Best-effort tracking — don't block user interaction
	});
}

sw.addEventListener('push', (event) => {
	if (!event.data) return;

	try {
		const payload = event.data.json() as {
			title: string;
			body: string;
			url?: string;
			icon?: string;
		};

		const tag = payload.url || 'missionnaire-notification';

		const options: NotificationOptions & { renotify?: boolean; actions?: { action: string; title: string; icon?: string }[] } = {
			body: payload.body,
			icon: payload.icon || '/favicon.png',
			badge: '/favicon.png',
			data: { url: payload.url || '/' },
			tag,
			renotify: true,
			actions: [
				{ action: 'open', title: 'Ouvrir' },
				{ action: 'dismiss', title: 'Ignorer' }
			]
		};

		event.waitUntil(
			sw.registration.showNotification(payload.title, options).then(() => {
				ackNotification('received', tag);
			})
		);
	} catch (e) {
		console.error('[SW] Error handling push event:', e);
	}
});

sw.addEventListener('notificationclick', (event) => {
	event.notification.close();

	const url = (event.notification.data?.url as string) || '/';
	const tag = event.notification.tag || 'unknown';
	const action = event.action || 'click';

	// Track that the user interacted with the notification
	ackNotification(action === 'dismiss' ? 'dismissed' : 'clicked', tag);

	// "dismiss" action — just close, don't navigate
	if (action === 'dismiss') return;

	event.waitUntil(
		sw.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
			// Focus an existing tab already on the target URL
			for (const client of clients) {
				if (new URL(client.url).pathname === url && 'focus' in client) {
					return client.focus();
				}
			}
			// Focus any existing tab on the same origin and navigate it
			for (const client of clients) {
				if (new URL(client.url).origin === sw.location.origin && 'focus' in client) {
					return client.focus().then((c) =>
						'navigate' in c ? c.navigate(url) : sw.clients.openWindow(url)
					);
				}
			}
			// Otherwise open a new window
			return sw.clients.openWindow(url);
		})
	);
});

// ── Fetch / Cache ─────────────────────────────────────────────────

sw.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Don't cache API requests or crawler files
	if (url.pathname.startsWith('/api/')) return;
	if (url.pathname === '/robots.txt' || url.pathname === '/sitemap.xml') return;

	// Cache YouTube thumbnails with long TTL
	if (url.hostname === 'i.ytimg.com') {
		event.respondWith(
			(async () => {
				const cache = await caches.open('yt-thumbnails');
				const cached = await cache.match(event.request);
				if (cached) return cached;

				const response = await fetch(event.request);
				if (response.ok) {
					cache.put(event.request, response.clone());
				}
				return response;
			})()
		);
		return;
	}

	// Don't cache other external URLs
	if (url.origin !== sw.location.origin) return;

	event.respondWith(
		(async () => {
			const cache = await caches.open(CACHE_NAME);

			// For build assets and static files, serve from cache first
			if (ASSETS.includes(url.pathname)) {
				const cached = await cache.match(event.request);
				if (cached) return cached;
			}

			// Navigation requests (HTML pages): stale-while-revalidate so the
			// installed app paints instantly from cache on launch instead of
			// waiting on a slow network — the cache is refreshed in the
			// background so the next visit sees fresh content. Eliminates the
			// "white screen on reopen" issue on flaky connections.
			if (event.request.mode === 'navigate') {
				const cached = await cache.match(event.request);
				const networkFetch = fetch(event.request)
					.then((response) => {
						if (response.status === 200) {
							cache.put(event.request, response.clone());
						}
						return response;
					})
					.catch(() => null);

				if (cached) {
					// Don't await — let the revalidation finish in the background.
					void networkFetch;
					return cached;
				}

				const fresh = await networkFetch;
				if (fresh) return fresh;

				const cachedIndex = await cache.match('/');
				if (cachedIndex) return cachedIndex;
				return new Response('Offline', { status: 503 });
			}

			// Subresources: network-first, fall back to cache on failure.
			try {
				const response = await fetch(event.request);
				if (response.status === 200) {
					cache.put(event.request, response.clone());
				}
				return response;
			} catch {
				const cached = await cache.match(event.request);
				if (cached) return cached;
				return new Response('Offline', { status: 503 });
			}
		})()
	);
});
