/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

const CACHE_NAME = `cache-${version}`;

// Assets generated by the build process and static files
const ASSETS = [...build, ...files];

sw.addEventListener('install', (event) => {
	event.waitUntil(
		caches
			.open(CACHE_NAME)
			.then((cache) => cache.addAll(ASSETS))
			.then(() => sw.skipWaiting())
	);
});

sw.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then(async (keys) => {
			for (const key of keys) {
				if (key !== CACHE_NAME) {
					await caches.delete(key);
				}
			}
			await sw.clients.claim();
		})
	);
});

// ── Push Notifications ────────────────────────────────────────────

sw.addEventListener('push', (event) => {
	if (!event.data) return;

	try {
		const payload = event.data.json() as {
			title: string;
			body: string;
			url?: string;
			icon?: string;
		};

		event.waitUntil(
			sw.registration.showNotification(payload.title, {
				body: payload.body,
				icon: payload.icon || '/favicon.png',
				badge: '/favicon.png',
				data: { url: payload.url || '/' }
			})
		);
	} catch (e) {
		console.error('[SW] Error handling push event:', e);
	}
});

sw.addEventListener('notificationclick', (event) => {
	event.notification.close();

	const url = (event.notification.data?.url as string) || '/';

	event.waitUntil(
		sw.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
			// Focus an existing tab if one is open on the same origin
			for (const client of clients) {
				if (new URL(client.url).origin === sw.location.origin && 'focus' in client) {
					client.focus();
					client.navigate(url);
					return;
				}
			}
			// Otherwise open a new window
			return sw.clients.openWindow(url);
		})
	);
});

// ── Fetch / Cache ─────────────────────────────────────────────────

sw.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Don't cache API requests or crawler files
	if (url.pathname.startsWith('/api/')) return;
	if (url.pathname === '/robots.txt' || url.pathname === '/sitemap.xml') return;

	// Cache YouTube thumbnails with long TTL
	if (url.hostname === 'i.ytimg.com') {
		event.respondWith(
			(async () => {
				const cache = await caches.open('yt-thumbnails');
				const cached = await cache.match(event.request);
				if (cached) return cached;

				const response = await fetch(event.request);
				if (response.ok) {
					cache.put(event.request, response.clone());
				}
				return response;
			})()
		);
		return;
	}

	// Don't cache other external URLs
	if (url.origin !== sw.location.origin) return;

	event.respondWith(
		(async () => {
			const cache = await caches.open(CACHE_NAME);

			// For build assets and static files, serve from cache first
			if (ASSETS.includes(url.pathname)) {
				const cached = await cache.match(event.request);
				if (cached) return cached;
			}

			// For pages, try network first, fall back to cache
			try {
				const response = await fetch(event.request);
				// Cache successful page responses
				if (response.status === 200) {
					cache.put(event.request, response.clone());
				}
				return response;
			} catch {
				const cached = await cache.match(event.request);
				if (cached) return cached;

				// If it's a navigation request and nothing is cached, return the offline page
				if (event.request.mode === 'navigate') {
					const cachedIndex = await cache.match('/');
					if (cachedIndex) return cachedIndex;
				}

				return new Response('Offline', { status: 503 });
			}
		})()
	);
});
