name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: missionnairenetwork # TODO: update Google Cloud project id
  SERVICE: missionnaire-website # TODO: update Cloud Run service name
  REGION: us-central1 # TODO: update Cloud Run service region
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
  YOUTUBE_CHANNEL_ID: UCS3zqpqnCvT0SFa_jI662Kg
  YOUTUBE_API_URL: https://youtube.googleapis.com/youtube/v3/search

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      
      # NOTE: Alternative option - authentication via credentials json
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.RUN_CREDS}}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If required, update to the appropriate source folder
          source: ./

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
