name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: missionnairenetwork
  SERVICE: missionnaire-website
  REGION: us-central1
  YOUTUBE_API_KEY: ${{secrets.YOUTUBE_API_KEY}}

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create .env file
        run: echo YOUTUBE_API_KEY=${{secrets.YOUTUBE_API_KEY}} > .env

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.RUN_CREDS}}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Deploy to Cloud Run
        id: deploy
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --source . \
            --project ${{ env.PROJECT_ID }} \
            --set-env-vars "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" \
            --allow-unauthenticated

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}